### ISSUE TITLE
Shoutbox not visible at login

### ISSUE THREAD

**Issue by TheZeph** [iamdansker/Far-Shiverpeaks-Development#33]
When logging in on the site (FF 37.0) I do not see the shoutbox with shouts.
It's plain empty.

When I press on into, example, the forum.. the shouts appear.

**Comment by vennekilde** [comment]
Did this happens once? or can you reproduce it every time?
I can't seem to do it on my end

**Comment by TheZeph** [comment]
Reproduced it @ work, @ home no problems... both on FF

**Comment by vennekilde** [comment]
i think i found the issue

it is when the domain has www. which then causes issues with cross domain scripting

Console Error: XMLHttpRequest cannot load http://farshiverpeaks.com/index.php?action=dream;sa=shoutbox;xml;get_shouts…id=shoutbox_mod_4;population=0;b7974fdacc=b2896ced3e4f9aa1e1136ac668f1058d. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.farshiverpeaks.com' is therefore not allowed access.

Should have a fix soon

**Comment by vennekilde** [comment]
instead of changing the shotubox plugin source, i just used the rewrite engine to redirect www

``` htaccess
RewriteEngine On
RewriteBase /
RewriteCond %{HTTP_HOST} ^www\.(.*)$ [NC]
RewriteRule ^(.*)$ http://%1/$1 [R=301,L]
```
