### ISSUE TITLE
Images cannot be aligned

### ISSUE THREAD

**Issue by TheZeph** [iamdansker/Far-Shiverpeaks-Development#34]
When posting a reply or OP, an image can be linked (ex. from imgurl.com).
What is shown in code is:
[img]http://i.imgur.com/D7zHbZY.png[/img]

When I do the same but align the image center, this is shown in code:

[font=Verdana][/font]

First line (where the image should be) is blank and then the font stuff comes...?

**Comment by vennekilde** [comment]
I have noticed that [font......] sometimes appear when you never put it there yourself and sometimes remove content you placed

I have always been able to just insert what i was trying to do again and it would work (try using the raw editor if having issues)
