### ISSUE TITLE
Messages on the forum 

### ISSUE THREAD

**Issue by TheZeph** [iamdansker/Far-Shiverpeaks-Development#35]
When I go to my inbox on the forum I have like 17 pages of messages in my inbox (old ones ofc.)
But when I received new ones, I couldn't read them.
The page automaticly started @ number 17.. which was blank, i finally found my latest messages on page 9?

Pages: 1 ... 7 8 [9] 10 11 ... 17

**Comment by vennekilde** [comment]
Seems the transfer created some fake message id's linking to messages that didn't exist, leading to more message pages than there was messages for

Fixed using 

``` sql
DELETE r 
FROM smf_pm_recipients r 
LEFT JOIN smf_personal_messages p 
ON r.id_pm = p.id_pm 
WHERE p.id_pm IS NULL
```

**Comment by vennekilde** [comment]
I am guessing it was due to the way phpfusion did messages by having them saved twice (one for reciever, one for sender)
