### ISSUE TITLE
Sidepanel doesn't show latest posts

### ISSUE THREAD

**Issue by Riekle** [iamdansker/Far-Shiverpeaks-Development#37]
For some reason since a week or 2 it seems the "latest posts" widget on the side panel seems gone. I'm not sure if this is a bug or intended but I find it rather annoying.
There are 2 widgets on the side panel (homepage and forum page) and those are the shoutbox and teamspeak widget.

This change seems to have fallen together with my forum position being upgraded to "TS Moderator" so it might be that that's what's causing the errors.

Regards, 
Coiler

**Comment by vennekilde** [comment]
Did this fix it?

**Comment by Riekle** [comment]
Yes it did, thanks a lot :+1:

**Comment by vennekilde** [comment]
Yeah it was just a permissions issue, ty for bringing it up :)
it took a month before people said that the news page was missing for every user in the Far Shiverpeaks membergroup :)

**Comment by Riekle** [comment]
You're very welcome, it seemed odd to me so I figured I might as well ask.
