### ISSUE TITLE
Video add button location - dark theme

### ISSUE THREAD

**Issue by Reload86** [iamdansker/Far-Shiverpeaks-Development#38]
The video add button on the dark theme dsiplays slightly higher than the video button which makes it impossible to move across to the add button before the menu dissappears.

Minor but was quite annoying earlier :)

**Comment by vennekilde** [comment]
Fixed
Also sorry i completely forgot about this issues, saw it while i wasn't home and forgot about it when i got home

Just got vacation now, so hopefully i can get some the other features implemented now
