### ISSUE TITLE
Acc. name on profile

### ISSUE THREAD

**Issue by KrijnvdBurg** [iamdansker/Far-Shiverpeaks-Development#39]
Is it possible to have Acc. name displayed on people their forum profile? Some users never post anything on which I cannot find their Account name. Or am I overlooking something?

**Comment by vennekilde** [comment]
That is the case for the moment being

I am planning on having it so it will be displayed on your profile page, however if i do that, i will also have an option to not show it.

I have had some concerned people telling me that they are not fond of the idea that all their information is available just to use the TS.

So i guess it would be default not show it and then turn it on once that user posts something

**Comment by KrijnvdBurg** [comment]
Alright that sounds fair enough that people don't want all their information available.

Another request would if the buttons on guild rosters for edit and remove could be behind each other and not under each other. Creates some white spacing between each member in the roster that only creates more scrolling. Would be nice if it could be more compact [😊]
- Lokar

---

Van: Jeppe Vennekilde notifications@github.com
Verzonden: maandag 19 oktober 2015 12:37
Aan: iamdansker/Far-Shiverpeaks-Development
CC: KrijnvdBurg
Onderwerp: Re: [Far-Shiverpeaks-Development] Acc. name on profile (#39)

That is the case for the moment being

I am planning on having it so it will be displayed on your profile page, however if i do that, i will also have an option to not show it.

I have had some concerned people telling me that they are not fond of the idea that all their information is available just to use the TS.

So i guess it would be default not show it and then turn it on once that user posts something

—
Reply to this email directly or view it on GitHubhttps://github.com/iamdansker/Far-Shiverpeaks-Development/issues/39#issuecomment-149179607.

[https://avatars1.githubusercontent.com/u/5627531?v=3&s=400]https://github.com/iamdansker/Far-Shiverpeaks-Development/issues/39#issuecomment-149179607

Acc. name on profile · Issue #39 · iamdansker/Far-Shiverpeaks-Developmenthttps://github.com/iamdansker/Far-Shiverpeaks-Development/issues/39#issuecomment-149179607
github.com
Is it possible to have Acc. name displayed on people their forum profile? Some users never post anything on which I cannot find their Account name. Or am I overlooking something?

**Comment by vennekilde** [comment]
Weird, looks like this for me http://i.imgur.com/fpaZpft.png

**Comment by KrijnvdBurg** [comment]
It used to look like that for me as well but for quite a long while (no idea how long exactly, sorry) it looks like this for me. http://i.imgur.com/5q3qpzV.jpg

Thought you changed it since it just went from your screenshot to what mine looks like from one day onto the other.

[http://i.imgur.com/5q3qpzV.jpg]

---

Van: Jeppe Vennekilde notifications@github.com
Verzonden: dinsdag 20 oktober 2015 16:08
Aan: iamdansker/Far-Shiverpeaks-Development
CC: KrijnvdBurg
Onderwerp: Re: [Far-Shiverpeaks-Development] Acc. name on profile (#39)

Weird, looks like this for me http://i.imgur.com/fpaZpft.png

[http://i.imgur.com/fpaZpft.png]

##
